// generated by tools/build_characters.py — character spritesheets (frame size, pivot, animations)
const CHAR_SHEETS = {
 "nico": {
  "src": "assets/chars/nico.webp",
  "fw": 206,
  "fh": 485,
  "cols": 8,
  "rows": 4,
  "pivot": [
   0.4431,
   0.9524
  ],
  "anims": {
   "idle": {
    "row": 0,
    "frames": 6,
    "fps": 6
   },
   "walk": {
    "row": 1,
    "frames": 8,
    "fps": 10
   },
   "jump": {
    "row": 2,
    "frames": 8,
    "fps": 12
   },
   "cheer": {
    "row": 3,
    "frames": 8,
    "fps": 10
   }
  }
 },
 "massie": {
  "src": "assets/chars/massie.webp",
  "fw": 221,
  "fh": 485,
  "cols": 8,
  "rows": 4,
  "pivot": [
   0.5,
   0.9692
  ],
  "anims": {
   "idle": {
    "row": 0,
    "frames": 6,
    "fps": 6
   },
   "walk": {
    "row": 1,
    "frames": 8,
    "fps": 10
   },
   "jump": {
    "row": 2,
    "frames": 8,
    "fps": 12
   },
   "cheer": {
    "row": 3,
    "frames": 8,
    "fps": 10
   }
  }
 },
 "luma": {
  "src": "assets/chars/luma.webp",
  "fw": 260,
  "fh": 379,
  "cols": 8,
  "rows": 4,
  "pivot": [
   0.3855,
   0.9867
  ],
  "anims": {
   "idle": {
    "row": 0,
    "frames": 6,
    "fps": 6
   },
   "walk": {
    "row": 1,
    "frames": 8,
    "fps": 10
   },
   "jump": {
    "row": 2,
    "frames": 8,
    "fps": 12
   },
   "cheer": {
    "row": 3,
    "frames": 8,
    "fps": 10
   }
  }
 },
 "luna": {
  "src": "assets/chars/luna.webp",
  "fw": 191,
  "fh": 382,
  "cols": 8,
  "rows": 4,
  "pivot": [
   0.3914,
   0.9907
  ],
  "anims": {
   "idle": {
    "row": 0,
    "frames": 6,
    "fps": 6
   },
   "walk": {
    "row": 1,
    "frames": 8,
    "fps": 10
   },
   "jump": {
    "row": 2,
    "frames": 8,
    "fps": 12
   },
   "cheer": {
    "row": 3,
    "frames": 8,
    "fps": 10
   }
  }
 }
};
