"""
Character spritesheets (exported from Sprite Forge) -> compact web sheets.
Run from the repo root:  python3 tools/build_characters.py
Input : tools/raw/sheets/{nico,massie}.png (RGBA) and {luma,luna}.jpg (white background)
Output: assets/chars/<name>.webp  + js/char-data.js
Each output sheet keeps only the animations the site uses (idle, walk, cheer, jump),
cropped tight around the character (same box for every frame, so the feet never jump),
background removed and alpha cleaned.
"""
import json, os
import numpy as np
from PIL import Image
import cv2

SRC = "tools/raw/sheets"
OUT = "assets/chars"
os.makedirs(OUT, exist_ok=True)
# original Sprite Forge layout: 8 columns x 8 rows; row index and frame count per animation
ANIMS = {"idle": (0, 6, 6), "walk": (1, 8, 10), "jump": (3, 8, 12), "cheer": (7, 8, 10)}  # row, frames, fps
CHARS = {
    #  name     file          pivotY  target content height (px)
    "nico":   ("nico.png",   0.94,   300),
    "massie": ("massie.png", 0.939,  300),
    "luma":   ("luma.jpg",   0.88,   240),
    "luna":   ("luna.jpg",   0.9095, 240),
}

def to_rgba(img, white_bg):
    a = np.array(img.convert("RGBA")).astype(np.float32)
    if white_bg:
        rgb = a[..., :3]
        # distance from white -> alpha, only for regions connected to the frame border
        mn = rgb.min(axis=2); sat = rgb.max(axis=2) - mn
        whiteish = ((mn > 228) & (sat < 22)).astype(np.uint8)
        n, lab = cv2.connectedComponents(whiteish, connectivity=4)
        border = set(np.unique(np.concatenate([lab[0], lab[-1], lab[:, 0], lab[:, -1]]))) - {0}
        bg = np.isin(lab, list(border))
        bg = cv2.dilate(bg.astype(np.uint8), np.ones((3, 3), np.uint8)).astype(bool)
        alpha = np.where(bg, 0, 255).astype(np.float32)
        alpha = cv2.GaussianBlur(alpha, (3, 3), 0)
        a[..., 3] = alpha
    else:
        al = a[..., 3]
        al[al < 60] = 0          # Sprite Forge left faint rectangles around some frames
        a[..., 3] = al
    # keep the main body (+ big pieces), drop specks
    m = (a[..., 3] > 40).astype(np.uint8)
    n, lab, st, _ = cv2.connectedComponentsWithStats(m, connectivity=8)
    if n > 1:
        big = st[1:, 4].max()
        keep = np.zeros_like(m, bool)
        for i in range(1, n):
            if st[i, 4] >= big * 0.06: keep |= lab == i
        keep = cv2.dilate(keep.astype(np.uint8), np.ones((3, 3), np.uint8)).astype(bool)
        a[..., 3] = np.where(keep, a[..., 3], 0)
    return Image.fromarray(a.clip(0, 255).astype(np.uint8))

meta = {}
for name, (file, pivy, target_h) in CHARS.items():
    sheet = Image.open(os.path.join(SRC, file))
    W, H = sheet.size
    fw, fh = W / 8, H / 8
    frames = {}
    for anim, (row, count, fps) in ANIMS.items():
        for i in range(count):
            box = (round(i * fw), round(row * fh), round((i + 1) * fw), round((row + 1) * fh))
            frames[(anim, i)] = to_rgba(sheet.crop(box), file.endswith(".jpg"))
    # union bounding box of all kept frames
    x0 = y0 = 10**9; x1 = y1 = 0
    for im in frames.values():
        bb = im.getbbox()
        if bb: x0, y0, x1, y1 = min(x0, bb[0]), min(y0, bb[1]), max(x1, bb[2]), max(y1, bb[3])
    pad = 6
    x0, y0 = max(0, x0 - pad), max(0, y0 - pad)
    x1, y1 = min(round(fw), x1 + pad), min(round(fh), y1 + pad)
    cw, ch = x1 - x0, y1 - y0
    # idle frame content height drives the scale
    ib = frames[("idle", 0)].getbbox()
    scale = target_h / (ib[3] - ib[1])
    ow, oh = max(1, round(cw * scale)), max(1, round(ch * scale))
    out = Image.new("RGBA", (ow * 8, oh * len(ANIMS)), (0, 0, 0, 0))
    anims = {}
    for r, (anim, (row, count, fps)) in enumerate(ANIMS.items()):
        for i in range(count):
            fr = frames[(anim, i)].crop((x0, y0, x1, y1)).resize((ow, oh), Image.LANCZOS)
            out.paste(fr, (i * ow, r * oh))
        anims[anim] = {"row": r, "frames": count, "fps": fps}
    out.save(os.path.join(OUT, name + ".webp"), "WEBP", quality=88, method=6)
    # pivot (feet) inside the cropped frame, as a fraction
    py = (pivy * fh - y0) / ch
    px = (fw / 2 - x0) / cw
    meta[name] = {"src": f"assets/chars/{name}.webp", "fw": ow, "fh": oh, "cols": 8, "rows": len(ANIMS),
                  "pivot": [round(px, 4), round(min(py, 1), 4)], "anims": anims}
    print(name, "frame", ow, "x", oh, "sheet", out.size, "kB", os.path.getsize(os.path.join(OUT, name + ".webp")) // 1024)

js = "// generated by tools/build_characters.py — character spritesheets (frame size, pivot, animations)\nconst CHAR_SHEETS = " + json.dumps(meta, indent=1) + ";\n"
open("js/char-data.js", "w").write(js)
