"""
Optional: bundle the site into ONE self-contained HTML file (dist/passgo-standalone.html),
handy for sharing offline or by email. GitHub Pages serves the normal multi-file site.
Run from the repo root:   python3 tools/build.py
- css/*.css and js/*.js referenced by index.html are inlined
- every assets/... image is embedded as a data: URI
  (images used from CSS are stored once as CSS variables)
External scripts (YouTube API, Google Fonts) stay external.
"""
import base64, mimetypes, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "dist", "passgo-standalone.html")
os.makedirs(os.path.dirname(OUT), exist_ok=True)
ASSET_RE = re.compile(r"(?:\.\./)?assets/[A-Za-z0-9_./-]+\.(?:png|jpe?g|webp|svg|gif|mp3)")
cache = {}

def data_uri(path):
    rel = path.replace("../", "")
    if rel not in cache:
        mime = {"webp": "image/webp", "mp3": "audio/mpeg"}.get(rel.rsplit(".", 1)[-1]) or mimetypes.guess_type(rel)[0] or "application/octet-stream"
        with open(os.path.join(ROOT, rel), "rb") as f:
            cache[rel] = f"data:{mime};base64," + base64.b64encode(f.read()).decode()
    return cache[rel]

def inline_css(css):
    used = sorted(set(m.group(0).replace("../", "") for m in ASSET_RE.finditer(css)))
    names = {p: "--asset-" + re.sub(r"[^a-z0-9]+", "-", p.lower()) for p in used}
    css = re.sub(r"url\((['\"]?)((?:\.\./)?assets/[^'\")]+)\1\)", lambda m: f"var({names[m.group(2).replace('../', '')]})", css)
    root = ":root{" + "".join(f"{names[p]}:url('{data_uri(p)}');" for p in used) + "}\n"
    return root + css

QUOTED_RE = re.compile(r"(?<=[\"'`])" + ASSET_RE.pattern + r"(?=[\"'`])")
def inline_assets(text):
    # only quoted paths (strings / attributes) — never paths mentioned in comments
    return QUOTED_RE.sub(lambda m: data_uri(m.group(0)), text)

html = open(os.path.join(ROOT, "index.html"), encoding="utf-8").read()
css_all = ""
def css_link(m):
    global css_all
    css_all += open(os.path.join(ROOT, m.group(1)), encoding="utf-8").read() + "\n"
    return "<!--CSS-->" if "<!--CSS-->" not in html_marker else ""
html_marker = ""
links = re.findall(r'<link rel="stylesheet" href="(css/[^"]+)">', html)
for i, href in enumerate(links):
    css_all += open(os.path.join(ROOT, href), encoding="utf-8").read() + "\n"
    html = html.replace(f'<link rel="stylesheet" href="{href}">', "<!--CSS-->" if i == 0 else "")
def js_tag(m):
    code = open(os.path.join(ROOT, m.group(1)), encoding="utf-8").read()
    return "<script>\n" + inline_assets(code).replace("</script", "<\\/script") + "\n</script>"
html = re.sub(r'<script src="(js/[^"]+)"></script>', js_tag, html)
# html attributes (img src) — scripts are already inlined, so only untouched paths remain
html = inline_assets(html)
html = html.replace("<!--CSS-->", "<style>\n" + inline_css(css_all) + "</style>")
html = html.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n<!-- PassGO! — standalone build generated by tools/build.py -->", 1)
open(OUT, "w", encoding="utf-8").write(html)
print(f"wrote {OUT}  ({len(html)/1e6:.2f} MB, {len(cache)} assets)")
